[package]
name = "calendar-desktop-notification"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = [ "blocking" ] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.2"
