[package]
name = "calendar-desktop-notification"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
web_ical = "0.1.2"
